spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reporting_db

  zipkin:
    base-url: http://localhost:9411/

  kafka:
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      
---
spring:
  profiles: ReportingService1
server:
  port: 8092

---
spring:
  profiles: ReportingService2
server:
  port: 8093
